#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

gnuplot gnuplot/004_plotUpng.gp
gnuplot gnuplot/102_forceCoeffspng.gp
#------------------------------------------------------------------------------
